### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by bh0085** [neighthan/gpu-utils#1]
Hey Nathan,
we need:
pynvml
psutil

to get started!
Thanks

**Comment by neighthan** [comment]
This should be fixed now - can you try reinstalling and confirm?

**Comment by bh0085** [comment]
WORKS! Thanks Nathan

**Comment by bh0085** [comment]
Proof:
![image](https://user-images.githubusercontent.com/225061/53976081-4a947b00-40d4-11e9-8b7f-e3cc56430bac.png)
